views:
  north_west:
    deg_0:
      base: none
    deg_90:
      base: none
    deg_180:
      base: none
    deg_270:
      base: none
  north_east:
    deg_0:
      base: none
    deg_90:
      base: none
    deg_180:
      base: none
    deg_270:
      base: none
  south_west:
    deg_0:
      base: none
    deg_90:
      base: none
    deg_180:
      base: none
    deg_270:
      base: none
  south_east:
    deg_0:
      base: none
    deg_90:
      base: none
    deg_180:
      base: none
    deg_270:
      base: none
